class Recipe {
  final String name;
  final List<String> ingredients;
  final List<String> instructions;

  Recipe({
    required this.name,
    required this.ingredients,
    required this.instructions,
  });
}

List<Recipe> sampleRecipes = [
  Recipe(
    name: 'Chicken Biryani',
    ingredients: [
      '1 kg chicken',
      '3 cups basmati rice',
      '4 onions (sliced)',
      '2 tbsp biryani masala',
      '1 cup yogurt',
      '4 green chilies',
      'Ginger-garlic paste',
      'Bay leaves and whole spices',
      'Saffron and milk',
      'Ghee and oil',
    ],
    instructions: [
      'Marinate chicken with yogurt, ginger-garlic paste, and biryani masala',
      'Parboil rice with whole spices until 70% cooked',
      'Fry onions until golden brown and crispy',
      'Layer marinated chicken in a pot',
      'Add fried onions and green chilies',
      'Layer parboiled rice on top',
      'Sprinkle saffron milk and ghee',
      'Cover and cook on low heat for 30 minutes (dum)',
      'Serve hot with raita',
    ],
  ),
  Recipe(
    name: 'Beef Tehari',
    ingredients: [
      '500g beef',
      '2 cups basmati rice',
      '3 potatoes (cubed)',
      '3 onions',
      '2 tbsp ginger-garlic paste',
      'Whole spices (cardamom, cinnamon, bay leaf)',
      'Turmeric and red chili powder',
      'Mustard oil',
      'Salt to taste',
    ],
    instructions: [
      'Heat mustard oil and fry potatoes until golden',
      'Fry onions until brown, remove half for garnish',
      'Add beef and ginger-garlic paste, cook until brown',
      'Add spices, turmeric, and chili powder',
      'Add water and cook beef until tender',
      'Add washed rice and mix well',
      'Add enough water to cover rice',
      'Cook on low heat until rice is done',
      'Garnish with fried onions and serve',
    ],
  ),
  Recipe(
    name: 'Chicken Rezala',
    ingredients: [
      '1 kg chicken',
      '1 cup yogurt',
      '4 green chilies',
      '2 tbsp poppy seeds',
      '10 cashew nuts',
      'Ginger-garlic paste',
      'Ghee',
      'Cardamom and cinnamon',
      'White pepper powder',
      'Salt to taste',
    ],
    instructions: [
      'Grind poppy seeds and cashews with water',
      'Marinate chicken with yogurt and ginger-garlic paste',
      'Heat ghee and add whole spices',
      'Add marinated chicken and cook until oil separates',
      'Add ground poppy seed and cashew paste',
      'Add green chilies and white pepper',
      'Cook on low heat until chicken is tender',
      'Garnish with fried onions',
      'Serve with polao or naan',
    ],
  ),
  Recipe(
    name: 'Kacchi Biryani',
    ingredients: [
      '1 kg mutton',
      '3 cups basmati rice',
      '1 cup yogurt',
      '5 onions',
      'Ginger-garlic paste',
      'Biryani masala',
      'Saffron and milk',
      'Ghee and oil',
      'Whole spices',
      'Salt to taste',
    ],
    instructions: [
      'Marinate mutton with yogurt, spices, and ginger-garlic paste for 2 hours',
      'Fry onions until dark brown and crispy',
      'Soak rice for 30 minutes',
      'Layer marinated raw mutton in a heavy pot',
      'Add half of the fried onions',
      'Layer soaked raw rice on top',
      'Add remaining onions, saffron milk, and ghee',
      'Seal pot with dough and cook on high for 5 minutes',
      'Reduce heat and cook for 45 minutes',
      'Let it rest for 10 minutes before serving',
    ],
  ),
  Recipe(
    name: 'Morog Polao (Chicken Pulao)',
    ingredients: [
      '500g chicken',
      '2 cups basmati rice',
      '3 onions',
      'Ginger-garlic paste',
      '1 cup yogurt',
      'Whole spices (bay leaf, cardamom, cinnamon)',
      'Ghee',
      'Raisins and cashews',
      'Salt to taste',
    ],
    instructions: [
      'Marinate chicken with yogurt and ginger-garlic paste',
      'Fry onions in ghee until golden',
      'Add marinated chicken and cook until done',
      'Add washed rice and mix well',
      'Add hot water (1:2 ratio)',
      'Add whole spices',
      'Cover and cook on low heat until rice is done',
      'Fry raisins and cashews separately',
      'Garnish polao with fried nuts and serve',
    ],
  ),
];